# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: myboard CI/CD Build

on:
  push:
    branches: [ main ]

name: Deploy String boot to Amazon EC2
env:
  PROJECT_NAME: action_codedeploy
  
jobs:
  build:
  #실행 환경 지정
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

    - name: Build with Gradle
      run: gradle build

    - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

    - name: Build with Gradle
      run: ./gradlew build
      shell: bash
